// <auto-generated />
using System;
using ComitatoFeste.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ComitatoFeste.Data.Migrations
{
    [DbContext(typeof(ComitatoFesteDbContext))]
    [Migration("20260902105831_AddMediaBlobs")]
    partial class AddMediaBlobs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ComitatoFeste.Domain.DigestPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int>("IngestionRunId")
                        .HasColumnType("integer");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("IngestionRunId");

                    b.HasIndex("MemberId");

                    b.HasIndex("Text")
                        .HasDatabaseName("IX_DigestPoints_Text_Trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Text"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Text"), new[] { "gin_trgm_ops" });

                    b.HasIndex("GroupId", "MemberId", "OccurredAt", "Text")
                        .IsUnique()
                        .HasDatabaseName("UX_DigestPoints_Group_Member_OccurredAt_Text");

                    b.ToTable("DigestPoints", null, t =>
                        {
                            t.HasCheckConstraint("CK_DigestPoints_Type", "\"Type\" IN ('decisione', 'domanda', 'media', 'info')");
                        });
                });

            modelBuilder.Entity("ComitatoFeste.Domain.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Groups", (string)null);
                });

            modelBuilder.Entity("ComitatoFeste.Domain.IngestionRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("SourceFile")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("WindowEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("WindowStart")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "WindowStart", "WindowEnd");

                    b.ToTable("IngestionRuns", (string)null);
                });

            modelBuilder.Entity("ComitatoFeste.Domain.MediaAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DigestPointId")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("TranscribedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TranscriptionText")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DigestPointId")
                        .IsUnique();

                    b.ToTable("MediaAssets", null, t =>
                        {
                            t.HasCheckConstraint("CK_MediaAssets_MediaType", "\"MediaType\" IN ('foto', 'audio', 'documento')");
                        });
                });

            modelBuilder.Entity("ComitatoFeste.Domain.MediaBlob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("MediaAssetId")
                        .HasColumnType("integer");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("MediaAssetId")
                        .IsUnique();

                    b.HasIndex("Sha256");

                    b.ToTable("MediaBlobs", (string)null);
                });

            modelBuilder.Entity("ComitatoFeste.Domain.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "DisplayName")
                        .IsUnique();

                    b.ToTable("Members", (string)null);
                });

            modelBuilder.Entity("ComitatoFeste.Domain.DigestPoint", b =>
                {
                    b.HasOne("ComitatoFeste.Domain.Group", "Group")
                        .WithMany("DigestPoints")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComitatoFeste.Domain.IngestionRun", "IngestionRun")
                        .WithMany("DigestPoints")
                        .HasForeignKey("IngestionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComitatoFeste.Domain.Member", "Member")
                        .WithMany("DigestPoints")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("IngestionRun");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("ComitatoFeste.Domain.IngestionRun", b =>
                {
                    b.HasOne("ComitatoFeste.Domain.Group", "Group")
                        .WithMany("IngestionRuns")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("ComitatoFeste.Domain.MediaAsset", b =>
                {
                    b.HasOne("ComitatoFeste.Domain.DigestPoint", "DigestPoint")
                        .WithOne("MediaAsset")
                        .HasForeignKey("ComitatoFeste.Domain.MediaAsset", "DigestPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DigestPoint");
                });

            modelBuilder.Entity("ComitatoFeste.Domain.MediaBlob", b =>
                {
                    b.HasOne("ComitatoFeste.Domain.MediaAsset", "MediaAsset")
                        .WithOne("Blob")
                        .HasForeignKey("ComitatoFeste.Domain.MediaBlob", "MediaAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaAsset");
                });

            modelBuilder.Entity("ComitatoFeste.Domain.Member", b =>
                {
                    b.HasOne("ComitatoFeste.Domain.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("ComitatoFeste.Domain.DigestPoint", b =>
                {
                    b.Navigation("MediaAsset");
                });

            modelBuilder.Entity("ComitatoFeste.Domain.Group", b =>
                {
                    b.Navigation("DigestPoints");

                    b.Navigation("IngestionRuns");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("ComitatoFeste.Domain.IngestionRun", b =>
                {
                    b.Navigation("DigestPoints");
                });

            modelBuilder.Entity("ComitatoFeste.Domain.MediaAsset", b =>
                {
                    b.Navigation("Blob");
                });

            modelBuilder.Entity("ComitatoFeste.Domain.Member", b =>
                {
                    b.Navigation("DigestPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
